# Generated by Django 3.2.3 on 2021-05-30 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_posts_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='user_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='tag_id',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='replies',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='reply_id',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='comment_id',
        ),
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogs.posts'),
        ),
        migrations.AddField(
            model_name='replies',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blogs.comments'),
        ),
        migrations.RemoveField(
            model_name='posts',
            name='dislikes',
        ),
        migrations.AddField(
            model_name='posts',
            name='dislikes',
            field=models.ManyToManyField(related_name='dislikes', to='blogs.Users'),
        ),
        migrations.RemoveField(
            model_name='posts',
            name='likes',
        ),
        migrations.AddField(
            model_name='posts',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='blogs.Users'),
        ),
    ]
