# Generated by Django 3.2.3 on 2021-05-31 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20210531_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='picture',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
