# Generated by Django 3.2.3 on 2021-05-31 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_posts_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='picture',
            field=models.ImageField(upload_to='images'),
        ),
    ]
