# Generated by Django 3.2.3 on 2021-05-31 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20210531_1601'),
        ('blogs', '0006_alter_posts_picture'),
    ]

    operations = [
    ]
