# Generated by Django 3.2.3 on 2021-06-01 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_alter_posts_picture'),
        ('blogs', '0007_merge_20210531_1638'),
    ]

    operations = [
    ]
