# Generated by Django 3.2.3 on 2021-06-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_merge_20210601_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to='blogs.Users'),
        ),
    ]
