# Generated by Django 3.2.1 on 2021-06-03 09:16

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0009_categories_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='defaultImage.png', storage=django.core.files.storage.FileSystemStorage(), upload_to='', verbose_name='profile picture')),
                ('undesired_words_count', models.IntegerField(default=0)),
                ('is_locked', models.BooleanField(default=False)),
                ('bio', models.TextField(default='', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
